on:
  push:
    branches:
      - joss-paper
      - main
  
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TeX and PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md
          args: '-k joss/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: joss/
